sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends unzip texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended etoolbox latex-xcolor texlive-pictures chktex xzdec
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
- sudo apt-get update
- sudo apt-get install miktex
script:
- mkdir _build
- mkdir -p /home/travis/texmf/tex/latex
- unzip -d /home/travis/texmf/tex/latex/ latex.zip
- texify.EXE -b -p --engine=pdftex --tex-option="--synctex=1" resume.tex
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build resume.tex
deploy:
  provider: script
  script: sh $TRAVIS_BUILD_DIR/.travis/push.sh
  skip_cleanup: true
  on:
    branch: master