sudo: required

language: ruby

services:
  - docker

before_install:
- mkdir -p build
- rm -rf build/*
- docker build -t my-resume .

script:
- docker run -i --rm -v ${PWD}/build:/output my-resume cp my-resume/resume.pdf /output

deploy:
  provider: script
  script: sh $TRAVIS_BUILD_DIR/.travis/push.sh
  skip_cleanup: true
  on:
    branch: master